### ISSUE TITLE
Play streaming audio

### ISSUE THREAD

**Issue by jaydeepw** [jaydeepw/audio-wife#2]

**Comment by ktaragorn** [comment]
I notice you already do `setAudioStreamType(STREAM_MUSIC)` is this beyond that?

**Comment by ktaragorn** [comment]
ah, showing buffering etc?

**Comment by jaydeepw** [comment]
When I quick searched about it last time, I remember it having more than just setting the stream type.

**Comment by ktaragorn** [comment]
It worked for me when i tried to play it, its just mostly UI stuff, load
async and show loader, then show buffering, etc. When i tried, I loaded in
main thread by doing setDataSource, and that basically locked up the screen
for a second or 2 until basic metadata downloaded i guess, otherwise i was
able to play after that

**Comment by jaydeepw** [comment]
OK. If that is so straight forward, thats very awesome.

**Comment by iffa** [comment]
Any update on this? I'd love to use this lib for my app if this was implemented

**Comment by jaydeepw** [comment]
Just set the url and call the play() method provided by the API.
I dont see anything to be changed in the library to stream the audio from a url.
Current API works.
